# Generated by Django 4.2 on 2023-08-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('description', models.TextField()),
                ('cover_image', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('format', models.CharField(max_length=50)),
                ('availability_status', models.BooleanField()),
                ('isbn', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_status', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('book_offered_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_exchanges', to='my_app.book')),
                ('book_requested_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_exchanges', to='my_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('preferences', models.JSONField()),
                ('registration_date', models.DateTimeField()),
                ('activation_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('user_reviewed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_reviews', to='my_app.user')),
                ('user_reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_reviews', to='my_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserExchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.exchange')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
                ('delivery_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.shippingaddress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='user_offering_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_exchanges', to='my_app.user'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user_requesting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_exchanges', to='my_app.user'),
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.author')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_file', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
            ],
        ),
    ]
